{{- if .Values.backend.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.name }}-secrets
  labels:
    app: {{ .Values.backend.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- range $key, $val := .Values.backend.secretEnv }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
