apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.name }}-config
  labels:
    app: {{ .Values.backend.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  {{- range $key, $val := .Values.backend.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
