[project]
name = "podai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=0.6.3",
    "docling>=2.34.0",
    "fastapi>=0.115.12",
    "python-multipart>=0.0.20",
    "sqlmodel>=0.0.24",
    "uvicorn[standard]>=0.34.2",
]

[dependency-groups]
dev = [
    "ruff>=0.11.10",
]
