import { searchSimilarChunks } from './vectorStoreService.js';
import { llmService } from './llmService.js';
import { createLogger } from '../config/logger.js';

const logger = createLogger('chat-service');

/**
 * Generate a chat response using RAG (Retrieval Augmented Generation)
 * 
 * @param question The user question
 * @param fileId The ID of the PDF file to use as context
 * @returns A response string generated by the LLM
 */
export async function generateChatResponse(question: string, fileId: string): Promise<string> {
  try {
    logger.info(`Generating chat response for question: "${question}" with file ID: ${fileId}`);
    
    // Use the chatWithPdf method from llmService directly since it handles context retrieval internally
    const response = await llmService.chatWithPdf(question, fileId);
    return response;
    
  } catch (error) {
    logger.error(`Error generating chat response: ${error}`);
    throw new Error(`Failed to generate chat response: ${error}`);
  }
}
