import { searchSimilarChunks } from './vectorStoreService';
import { generateResponse } from './llmService';
import { createLogger } from '../config/logger';

const logger = createLogger('chat-service');

/**
 * Generate a chat response using RAG (Retrieval Augmented Generation)
 * 
 * @param question The user question
 * @param fileId The ID of the PDF file to use as context
 * @returns A response string generated by the LLM
 */
export async function generateChatResponse(question: string, fileId: string): Promise<string> {
  try {
    logger.info(`Generating chat response for question: "${question}" with file ID: ${fileId}`);
    
    // Retrieve relevant chunks from the vector store
    const similarChunks = await searchSimilarChunks(question, fileId);
    
    if (!similarChunks || similarChunks.length === 0) {
      logger.warn(`No similar chunks found for question: "${question}"`);
      return "I couldn't find any relevant information to answer your question.";
    }
    
    // Build context from the chunks
    const context = similarChunks
      .map(chunk => chunk.text)
      .join('\n\n');
    
    logger.info(`Found ${similarChunks.length} relevant chunks for context`);
    
    // Generate response using LLM with the retrieved context
    const response = await generateResponse(question, context);
    
    return response;
  } catch (error) {
    logger.error(`Error generating chat response: ${error}`);
    throw new Error(`Failed to generate chat response: ${error}`);
  }
}
